# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraExif' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CameraExif

  target 'CameraExifTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CameraExifUITests' do
    # Pods for testing
  end

  pod 'CryptoSwift', '~> 1.4.1'
pod 'SwiftyRSA'
end
